name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main    # or your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read   # allow checkout
      pages: write     # allow publishing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build the site
        run: npm run build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
